AWSTemplateFormatVersion: '2010-09-09'
Description: Wild Rydes DevOps Pipeline with Alarms - Created by Saravanan

Parameters:
  GitHubOwner:
    Type: String
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
    Default: main
  NotificationEmail:
    Type: String

Resources:

###############################################
# NETWORKING
###############################################

  SaravananVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Saravanan-VPC

  SaravananIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Saravanan-IGW

  SaravananAttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SaravananVPC
      InternetGatewayId: !Ref SaravananIGW

  SaravananPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SaravananVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Public-Subnet-A

  SaravananPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SaravananVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Public-Subnet-B

  SaravananPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SaravananVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Private-Subnet-A

  SaravananPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SaravananVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Private-Subnet-B

###############################################
# NAT + ROUTING
###############################################

  SaravananEIP:
    Type: AWS::EC2::EIP
    DependsOn: SaravananAttachIGW
    Properties:
      Domain: vpc

  SaravananNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt SaravananEIP.AllocationId
      SubnetId: !Ref SaravananPublicSubnet1
      Tags:
        - Key: Name
          Value: Saravanan-NAT

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SaravananVPC
      Tags:
        - Key: Name
          Value: Public-RT

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SaravananIGW

  PublicSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SaravananPublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SaravananPublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SaravananVPC
      Tags:
        - Key: Name
          Value: Private-RT

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref SaravananNATGateway

  PrivateSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SaravananPrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SaravananPrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

###############################################
# SECURITY GROUPS
###############################################

  SaravananALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !Ref SaravananVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SaravananECSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS SG
      VpcId: !Ref SaravananVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref SaravananALBSG

###############################################
# LOAD BALANCER
###############################################

  SaravananALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - !Ref SaravananPublicSubnet1
        - !Ref SaravananPublicSubnet2
      SecurityGroups:
        - !Ref SaravananALBSG

  SaravananTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref SaravananVPC
      TargetType: ip

  SaravananListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref SaravananALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref SaravananTG

###############################################
# ECR
###############################################

  SaravananECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: saravanan-repo

###############################################
# ECS FARGATE
###############################################

  SaravananCluster:
    Type: AWS::ECS::Cluster

  SaravananTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  SaravananTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: saravanan-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref SaravananTaskRole
      ContainerDefinitions:
        - Name: saravanan-container
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/saravanan-repo:latest'
          PortMappings:
            - ContainerPort: 80

  SaravananService:
    Type: AWS::ECS::Service
    DependsOn: SaravananListener
    Properties:
      Cluster: !Ref SaravananCluster
      TaskDefinition: !Ref SaravananTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: saravanan-container
          ContainerPort: 80
          TargetGroupArn: !Ref SaravananTG
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref SaravananPrivateSubnet1
            - !Ref SaravananPrivateSubnet2
          SecurityGroups:
            - !Ref SaravananECSSG

###############################################
# S3 BUCKET
###############################################

  SaravananArtifactBucket:
    Type: AWS::S3::Bucket

###############################################
# IAM
###############################################

  SaravananPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SaravananPipelineInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - ecs:*
                  - iam:PassRole
                  - codestar-connections:UseConnection
                Resource: "*"

  SaravananCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess

###############################################
# CODEBUILD
###############################################

  SaravananCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: saravanan-build
      ServiceRole: !Ref SaravananCodeBuildRole
      Environment:
        PrivilegedMode: true
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Sub '${AWS::Region}'
          - Name: AWS_ACCOUNT_ID
            Value: !Sub '${AWS::AccountId}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - REPO_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/saravanan-repo
                - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REPO_URI}
            build:
              commands:
                - docker build -t ${REPO_URI}:latest .
            post_build:
              commands:
                - docker push ${REPO_URI}:latest
                - printf '[{"name":"saravanan-container","imageUri":"%s"}]' ${REPO_URI}:latest > imagedefinitions.json
          artifacts:
            files:
              - imagedefinitions.json
      Artifacts:
        Type: CODEPIPELINE

###############################################
# SNS + EMAIL
###############################################

  SaravananSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: saravanan-pipeline-alarms

  SaravananSNSEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SaravananSNSTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

###############################################
# CODEPIPELINE
###############################################

  SaravananPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: saravanan-pipeline
      RoleArn: !GetAtt SaravananPipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref SaravananArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: arn:aws:codeconnections:ca-central-1:794038224942:connection/0674a0f1-283e-4843-95e8-d76cd1d8ad0f
                FullRepositoryId: !Sub '${GitHubOwner}/${GitHubRepo}'
                BranchName: !Ref GitHubBranch

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref SaravananCodeBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployToECS
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ClusterName: !Ref SaravananCluster
                ServiceName: !Ref SaravananService
                FileName: imagedefinitions.json

###############################################
# CLOUDWATCH ALARMS
###############################################

  SaravananSourceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Source stage failure
      Namespace: AWS/CodePipeline
      MetricName: StageExecutionFailed
      Dimensions:
        - Name: PipelineName
          Value: saravanan-pipeline
        - Name: StageName
          Value: Source
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SaravananSNSTopic

  SaravananBuildAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Build stage failure
      Namespace: AWS/CodePipeline
      MetricName: StageExecutionFailed
      Dimensions:
        - Name: PipelineName
          Value: saravanan-pipeline
        - Name: StageName
          Value: Build
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SaravananSNSTopic

  SaravananDeployAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Deploy stage failure
      Namespace: AWS/CodePipeline
      MetricName: StageExecutionFailed
      Dimensions:
        - Name: PipelineName
          Value: saravanan-pipeline
        - Name: StageName
          Value: Deploy
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SaravananSNSTopic

  SaravananPipelineAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Entire pipeline failure
      Namespace: AWS/CodePipeline
      MetricName: FailedExecutions
      Dimensions:
        - Name: PipelineName
          Value: saravanan-pipeline
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SaravananSNSTopic

###############################################
# OUTPUTS
###############################################

Outputs:
  LoadBalancerURL:
    Description: Public ALB URL
    Value: !GetAtt SaravananALB.DNSName
